site_name: lionel的技术笔记
theme: readthedocs
#theme: material
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#markdown_extensions:
#  - mdx_truly_sane_lists
#  - mdx_math:
#      enable_dollar_delimiter: True  #for use of inline $..$
markdown_extensions:
  - mdx_truly_sane_lists
#  - mdx_math:
 #     enable_dollar_delimiter: True  #for use of inline $..$
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
 # - pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
   #   emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等

nav:
    - 简介: 'index.md'
    - daily: '01daily.md'
    - C++: 
        - 《Effective C++》: '20C++/effectiveC++.md'
        - 《Effective STL》: '21STL/EffectiveSTL.md'
        - 《C++泛型STL原理和应用》: '21STL/C++泛型STL原理和应用.md'
        - 《深入应用C++11》: '22C++modern/深入应用C++11.md'
    - 基础知识:
        - 《操作系统导论》: '408/操作系统导论.md'
        - 《大话设计模式》: '408/大话设计模式.md'
    - 网络编程:
        - 《TCP/IP网络编程》: '10network/TCPIP网络编程.md'
        - 《Linux高性能服务器编程》: '10network/Linux高性能服务器编程.md'
        - 《TCPIP详解卷1》: '10network/TCPIP详解卷1.md'
        - 《Linux内核网络栈源代码情景分析》: '10network/Linux内核网络栈源代码情景分析.md'
        - 《深入理解Linux网络》: '10network/深入理解Linux网络.md'       
    - 文件系统:
        - 《Linux内核探秘》: '11filesystem/Linux内核探秘.md'
        - 《文件系统技术内幕》: '11filesystem/文件系统技术内幕.md'
        - 《存储技术原理分析》: '11filesystem/存储技术原理分析.md'
    - 存储:
        - 《ceph设计原理与实现》: '12storage/ceph设计原理与实现.md'
    - 视频:
        - 《FFmpeg入门到精通》: '14video/FFmpeg入门到精通.md'
        - 《WebRTC权威指南》: '14video/WebRTC权威指南.md'     
        - 《WebRTC音视频实时互动技术》: '14video/WebRTC音视频实时互动技术.md'
        - 《新一代视频压缩码标准-H.264_AVC》: '14video/新一代视频压缩码标准-H.264_AVC.md'
    - 内核:
        - 《Linux内核设计与实现》: '13kernel/Linux内核设计与实现.md'
        - 《深入Linux设备驱动程序内核机制》: '13kernel/深入Linux设备驱动程序内核机制.md'
        - 《深入理解Linux虚拟内存管理》: '13kernel/深入理解Linux虚拟内存管理.md'
        - 《深入理解Linux网络技术内幕》: '13kernel/深入理解Linux网络技术内幕.md'
        - 《深入理解Linux内核》: '13kernel/深入理解Linux内核.md'
    - 工具:
        - 《Wireshark网络分析实战》: '15tool/Wireshark网络分析实战.md' 
        - 《Linux命令行与shell脚本编程大全(3rd)》: '15tool/Linux命令行与shell脚本编程大全(3rd).md' 
        - 《python程序设计（3rd）》: '15tool/python程序设计（3rd）.md' 
    - 刷题:
        - 《剑指offer专项突破》: '91leetcode/剑指offer专项突破.md'
    - 网课:
        - 《Linux高并发网络编程开发》: '90lecture/01Linux高并发网络编程开发.md'
        - 《侯捷C++内存管理60讲》: '90lecture/侯捷/侯捷C++内存管理60讲.md'
        - 《NJU算法设计与分析》: '90lecture/11NJU算法设计与分析.md'
    - 英语专:
        - 《综合英语(一)上》: '60English/00794综合英语一上.md'
