site_name: lionel的技术笔记
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#markdown_extensions:
#  - mdx_truly_sane_lists
#  - mdx_math:
#      enable_dollar_delimiter: True  #for use of inline $..$

nav:
    - 简介: 'index.md'
    - 网络编程:
        - 《TCP/IP网络编程》: '10network/TCPIP网络编程.md'
