site_name: lionel的技术笔记
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#markdown_extensions:
#  - mdx_truly_sane_lists
#  - mdx_math:
#      enable_dollar_delimiter: True  #for use of inline $..$

nav:
    - 简介: 'index.md'
    - daily: '01daily.md'
    - 网络编程:
        - 《TCP/IP网络编程》: '10network/TCPIP网络编程.md'
        - 《Linux高性能服务器编程》: '10network/Linux高性能服务器编程.md'
    - 文件系统:
        - 《Linux内核探秘》: '11filesystem/Linux内核探秘.md'
        - 《文件系统技术内幕》: '11filesystem/文件系统技术内幕.md'
        - 《存储技术原理分析》: '11filesystem/存储技术原理分析.md'
    - 存储:
        - 《ceph设计原理与实现》: '12storage/ceph设计原理与实现.md'
    - 网课:
        - 《Linux高并发网络编程开发》: '90lecture/01Linux高并发网络编程开发.md'
